# Generated by Django 4.0.2 on 2022-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_intake_track_remove_myuser_id_alter_myuser_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
