# Generated by Django 4.0.2 on 2022-02-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_student_intake_id_alter_student_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='intake_id',
            new_name='intake',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='track_id',
            new_name='track',
        ),
    ]
